### ISSUE TITLE
beautiful app.  couple suggestions

### ISSUE THREAD

**Issue by jawz101** [SpicyChair/pluvia_weather_flutter#1]
Widgets and F-Droid.  This really is too nice to not F-Droid some love on F-Droid.

And every weather app needs widgets.  You are good with design so I bet they'd look great.

**Comment by SpicyChair** [comment]
Hey there,

Thanks for your support. 

I'll look into F-Droids inclusion policy and see if Pluvia Weather is compatible. As for widgets, I'll also look into if Flutter has added support for home screen widgets yet.

**Comment by SpicyChair** [comment]
I have requested for FDroid packaging on their repo.

https://gitlab.com/fdroid/rfp/-/issues/1823
