### ISSUE TITLE
why is this app gsf dependent?

### ISSUE THREAD

**Issue by zer0fl0w** [SpicyChair/pluvia_weather_flutter#12]
hi,

very nice and visual pleasing app.
maybe redundant question to closed issue #3, but
why is this app play services dependent? i do not see the necessity. can you please explain?
sadly i can not really use it atm because of it.

thanks.

**Comment by SpicyChair** [comment]
Hmm, that's strange. It might be the location package I use - I'll look into it.

Does the app not run at all? Or does it get stuck on finding location?

**Comment by zer0fl0w** [comment]
the app itself works.
i do not use location (gps).
i just manually add fixed places/cities via your search function.

but without installed play services the app always shows a pop-up and notification that play services are not available and that it is needed for the app to work.

**Comment by SpicyChair** [comment]
Could you send a screenshot of the notification and the pop-up?

**Comment by zer0fl0w** [comment]
@SpicyChair 

[https://upload.disroot.org/r/hM0TX52C#1SQSmxO2Dw6S1BlnEuq65Vi1kVD2M3OB9qX5iIFr7XA=](url)  

[https://upload.disroot.org/r/n9vr3cn6#yj7Bc2YP1/89N37YSroDZYtyAunYmxbf7jXro2POPrE=](url) 

i can ignore those and the app works fine.

it is just a bit annoyning for ux.
it is on latest oxygen os based on android 11, device is oneplus 8t.

**Comment by SpicyChair** [comment]
Could you please update to [https://github.com/SpicyChair/pluvia_weather_flutter/releases](Release v1.4.1) and see if the issue persists after setting a default location?

I can't seem to pinpoint the cause of the notifications, but please disable notifications for Pluvia Weather in Android settings.

**Comment by zer0fl0w** [comment]
updated to 1.4.1. it seems to work now.
i disabled the notifications. sometimes the pop-up still shows, but rarely. before it was everytime when i open the app.

so it is definitly a improvment.

thanks a lot for the help.

**Comment by zer0fl0w** [comment]
so i could track it.
if i leave the app with back button/gesture and reopen it
the pop-up shows.
if i leave app with home button/gesture and swipe it away from recents app and reopen it the pop-up does not show.

but this probably very specific behavior with my device/settings.

**Comment by SpicyChair** [comment]
Brilliant, thanks for testing. 

I'll keep on looking into the cause.

**Comment by SpicyChair** [comment]
@zer0fl0w Hi there,

I've removed GMS dependency from Release v1.4.3 onwards. Could you test it to see if the issue persists?

**Comment by zer0fl0w** [comment]
thank you so much. it is perfect now.
