### ISSUE TITLE
in screens/api_key_screen.dart error: Expected an identifier.

### ISSUE THREAD

**Issue by mayurpatilin** [SpicyChair/pluvia_weather_flutter#13]
error: Expected an identifier. (missing_identifier at [flutter_weather] lib/screens/api_key_screen.dart:19)
[
<img width="1440" alt="Screenshot 2021-08-12 at 1 38 55 PM" src="https://user-images.githubusercontent.com/51021871/129161739-27a12659-39a6-414a-a230-c13d297e9ba0.png">
](url)

**Comment by SpicyChair** [comment]
Hi there,

That's my mistake, this screen isn't actually used anymore. I will remove it from the repo.

Thanks for bringing it up
