### ISSUE TITLE
settings do not stick

### ISSUE THREAD

**Issue by zer0fl0w** [SpicyChair/pluvia_weather_flutter#14]
settings randomly reset itselfs.
happens for dark mode and 24 hour time.

it is reproduceable.

go to settings. enable 24 hour. enable dark mode.
go to settings again. disable dark mode.
go to settings again. 24 hour is disabled.

also dark mode enables itself sometimes.
could not reliable trigger it. seems random.

edit:
enable 24 hour. close the app. open the app.
dark mode is enabled.

**Comment by SpicyChair** [comment]
Fixed. Thanks for brining this up.
