### ISSUE TITLE
cant see any weather data

### ISSUE THREAD

**Issue by zer0fl0w** [SpicyChair/pluvia_weather_flutter#17]
pluvia somewhat stopped showing weather data.
i can still add places, like cities and set default location and so on. but when i go current or forecast tab it wont show weather data but only 'choose a location to view weather' although i already have chosen a location and also set default too. installed version is latest. i already tried clearing app-data and new install for no good.

anyone experienced same behavior?

**Comment by SpicyChair** [comment]
Yep. OpenWeather has disabled my API key. 

No notices or anything from them, so I'm pretty annoyed about it.

**Comment by SpicyChair** [comment]
Please for the time being use your own custom API key

**Comment by zer0fl0w** [comment]
setting own openweather key also does not work.
or have i set also mapbox key?

maybe api from openweather is down atm?

**Comment by SpicyChair** [comment]
Could you please check the API key is entered in properly, with no whitespace. This is because if the request is bad the app will try to use the default API Key (which is blocked)

**Comment by SpicyChair** [comment]
I've checked OpenWeather, no issues on their end

**Comment by zer0fl0w** [comment]
i am pretty sure i entered it correctly.

**Comment by SpicyChair** [comment]
I'll look into the custom API key error.

**Comment by zer0fl0w** [comment]
np. i just hope i am not much of a pita. 

(:

**Comment by SpicyChair** [comment]
Ah, no worries, I appreciate your help and testing :)

Could you please check if your OpenWeather API key works in v1.4.4 (latest release)?

**Comment by zer0fl0w** [comment]
it shows weather data again.

but dunno if it is my key, because when i past my key and leave advance and re-enter advanced it is not shown anymore. maybe it is supposed behavior.
when you did not set a new default key with v1.4.4, then its working because of my own key, since weather data is available again.

thanks.

**Comment by SpicyChair** [comment]
I uploaded the wrong apk file to releases, oops!

There is an updated apk file on the latest release. Hopefully, the api key should show when you leave and re enter advanced settings.

**Comment by zer0fl0w** [comment]
works now.

my own key is shown. even after leaving and re-entering advanced.

weather data is available and shown.

all fine. thanks a lot.
