### ISSUE TITLE
little cosmetical ui refinement needed

### ISSUE THREAD

**Issue by zer0fl0w** [SpicyChair/pluvia_weather_flutter#18]
in current tab there is a small misalignment.
the space from bubble/card for weather radar is to narrow from the divider above. all the other spaces above and under divider have fixed symetrical distance. only the weather radar is to close to its divider line above.

i hope what i try to tell is understandable.

**Comment by SpicyChair** [comment]
Could you take a screenshot?

Thanks

**Comment by zer0fl0w** [comment]
http://tinyimg.io/i/bqCKczj.jpg

green space is fine.

red space is not. (too narrow)

...for symetrical reasons.

**Comment by zer0fl0w** [comment]
v1.4.6 is fine now regarding the issue.
you fixed it. thanks.
