### ISSUE TITLE
new update is stuck at loading screen

### ISSUE THREAD

**Issue by mayurpatilin** [SpicyChair/pluvia_weather_flutter#20]
the app is stuck at loading screen its not opening home screen
<img width="1440" alt="Screenshot 2021-08-23 at 6 18 11 PM" src="https://user-images.githubusercontent.com/51021871/130449953-0b2b7f16-01e4-4ffd-8f3d-0c8ad6111ea2.png">

**Comment by SpicyChair** [comment]
Hi there,

I don't have this issue on my virtual device or real device.

Could you verify that you have "version: 1.4.5+27" in your pubspec.yaml?

**Comment by mayurpatilin** [comment]
yes its same but its not opening Home Screen I don't what wrong virtual device I will check it on real device

thank you
