### ISSUE TITLE
Temperature overlapping city name

### ISSUE THREAD

**Issue by whats-a-diorama** [SpicyChair/pluvia_weather_flutter#25]
Love the app. It's gorgeous, and has all the information that I'm looking for. Thank you for all of the work you've put into it!

I've just had one consistent minor cosmetic issue that I thought I'd report. The temperature display is always overlapping the city name on my device. So it never quite lines up with how it looks in the screenshots. I attached a screenshot of my own as an example. Sometimes it looks a little worse, depending on the numbers.

I haven't noticed anything like this anywhere else in the app.

F-Droid build of Pluvia, version 1.4.5. Pixel 5a (2400x1080 resolution), Android 11.

![pluvia-temperature](https://user-images.githubusercontent.com/90749317/133386134-b0a2c176-98bb-476d-9331-0006ccdef36c.png)

**Comment by SpicyChair** [comment]
Thank you for your support!

That's an interesting bug I haven't seen before - what is your DPI/Scaling?

**Comment by stringent-updoc** [comment]
My "Display size" configuration is set to "Default", which appears to be a DPI of 420. I do have my "Font size" configuration set to "Small", which is one step below "Default". But changing it back to "Default" doesn't appear to resolve the issue, unfortunately. Everything will be a little bigger, but still positioned identically.

**Comment by whats-a-diorama** [comment]
Hi. Just wanted to add that I've since upgraded to Android 12, but unfortunately that didn't have any impact on the issue. It still looks exactly the same.

(Though outside of that, the app is working great for me in Android 12!)

**Comment by Max1mus25** [comment]
Greetings, want to thank you for creating this cool app.
Writing this message here because it could be relative to this issue and if it's an issue at all.
![Screenshot_20220103-093839909_1](https://user-images.githubusercontent.com/72336357/147908537-f92bdcdd-aeca-4e31-a0d7-2aee25a822d5.jpg)

**Comment by n8x0b7T** [comment]
Instead of the city name being in the top bar, the city name text and refresh button should be in the same container as the temperature text. This would eliminate all the above issues.

**Comment by SpicyChair** [comment]
@n8x0b7T Good spot, thanks - I'll add this today
