### ISSUE TITLE
Padding on Current Weather Page

### ISSUE THREAD

**Issue by n8x0b7T** [SpicyChair/pluvia_weather_flutter#54]
The padding above the current temperature is zero. The location name has no space below it.

**Comment by n8x0b7T** [comment]
Instead of just a text widget, put the text in a container and give it top padding. 
Here is the code that needs to be changed:
https://github.com/SpicyChair/pluvia_weather_flutter/blob/cb9aa1be923ff571611ba8049442f4e8b679ccc8/lib/screens/current_weather_screen.dart#L294

**Comment by SpicyChair** [comment]
Added padding in latest release. Thanks
