### ISSUE TITLE
Dark mode search text

### ISSUE THREAD

**Issue by n8x0b7T** [SpicyChair/pluvia_weather_flutter#57]
Text appears invisible when searching for new locations in dark mode

**Comment by tejasraman** [comment]
Same here. I'm on Android 13 on a Pixel 6a. @SpicyChair I'm assuming this is just the wrong color code somewhere, could this be fixed in the next release? This app is one of the best weather apps I've tried but my phone is perpetually in dark mode

**Comment by SpicyChair** [comment]
Fixed on latest build
