### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Donkey-Doug** [SpicyChair/pluvia_weather_flutter#6]
The outlines on the bottom are cut off:

![Screenshot_20210725-000809_Pluvia](https://user-images.githubusercontent.com/50382414/126882123-9afa5b73-7f07-45ff-b6c1-915f7e6e3a7e.png)

**Comment by SpicyChair** [comment]
Hi there,

This should be fixed in the next release.

Thanks

**Comment by SpicyChair** [comment]
Could you check if this issue persists in v1.4.0? @Donkey-Doug
