### ISSUE TITLE
Status bar visual bug

### ISSUE THREAD

**Issue by Donkey-Doug** [SpicyChair/pluvia_weather_flutter#7]
The app seems to enforce somekind of shadow on the status bar. The text in the statusbar is not readable:

![Screenshot_20210725-000809_Pluvia](https://user-images.githubusercontent.com/50382414/126882156-33897065-5641-4d74-8239-ba8f5b4115c6.png)

**Comment by SpicyChair** [comment]
Should be fixed in latest version.

In current_weather_screen.dart:
 `return Scaffold(
      appBar: AppBar(
        brightness: Brightness.dark`
